include:
  - ./testing.yml

services:
  database:
    build:
      context: build/mysql
    container_name: anilibrary-database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u$DB_USER", "-p$DB_PASSWORD",  "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - ${DB_PORT}:3306
    networks:
      - local

  redis:
    image: redis:${REDIS_VERSION}
    container_name: anilibrary-redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $REDIS_PASSWORD ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - local

  nginx:
    depends_on:
      app:
        condition: service_healthy
    build:
      context: build/nginx
    container_name: anilibrary-nginx
    environment:
      NGINX_LOGS_TO_LOGSTASH: ${NGINX_LOGS_TO_LOGSTASH}
    volumes:
      - ./src/public:/anilibrary/public
    ports:
      - ${SERVER_PORT}:80
    networks:
      - local
      - anilibrary

  app: &app
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: build/php
    container_name: anilibrary
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
      CONTAINER_MODE: octane
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    extra_hosts:
      - "host.docker.internal:host-gateway" # for xdebug
    healthcheck:
      test: php artisan octane:status || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./src:/anilibrary
    ports:
      - ${NODE_PORT}:5173
    networks:
      - local
      - anilibrary

  horizon:
    <<: *app
    depends_on:
      app:
        condition: service_healthy
    container_name: anilibrary-horizon
    environment:
      CONTAINER_MODE: horizon
    healthcheck:
      test: php artisan horizon:status || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports: [ ]
    networks:
      - local

  scheduler:
    <<: *app
    depends_on:
      app:
        condition: service_healthy
    container_name: anilibrary-scheduler
    environment:
      CONTAINER_MODE: scheduler
    healthcheck:
      test: ps aux | grep 'php artisan schedule:work' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports: [ ]
    networks:
      - local

  telegram:
    <<: *app
    depends_on:
      app:
        condition: service_healthy
    container_name: anilibrary-telegram
    environment:
      CONTAINER_MODE: telegram
    healthcheck:
      test: ps aux | grep 'php artisan nutgram:run' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports: [ ]
    networks:
      - local

  reverb:
    <<: *app
    depends_on:
      app:
        condition: service_healthy
    container_name: anilibrary-reverb
    healthcheck:
      test: ps aux | grep 'php artisan reverb:start' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      CONTAINER_MODE: reverb
    ports: [ ]
    networks:
      - local

networks:
  anilibrary:
    name: anilibrary
  local:
    name: anilibrary-local

volumes:
  db-data:
    name: anilibrary-db-data
  redis-data:
    name: anilibrary-redis-data
