version: '3.9'

networks:
  backend:

services:
  app:
    build:
      args:
        GROUP_ID: ${GROUP_ID:-1000}
        USER_ID: ${USER_ID:-1000}
      context: ./
      dockerfile: ./php/php.Dockerfile
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    container_name: php
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./app:/anilibrary
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./supervisor/conf.d/:/etc/supervisor/conf.d/
    networks:
      backend:

  database:
    build:
      context: ./mysql
      dockerfile: ./mysql.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: anilibrary
      MYSQL_USER: u_anilibrary
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-default}
    container_name: database
    tty: true
    volumes:
    - ./runtime/mysql:/var/lib/mysql:rw
    ports:
    - ${MYSQL_PORT:-3306}:3306
    networks:
      backend:

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
    - "7760:80"
    networks:
      backend:

  redis:
    image: redis:6.2.6
    container_name: redis
    hostname: ${REDIS_HOSTNAME:-localhost}
    command: redis-server --requirepass ${REDIS_PASSWORD:-default}
    volumes:
      - ./runtime/redis/:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      backend:

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=${REDIS_HOSTS:-local:redis:${REDIS_PORT}:0:${REDIS_PASSWORD}}
    ports:
      - "8081:8081"
    networks:
      backend: