version: '3.9'

networks:
  backend:

services:
  app:
    build:
      args:
        GROUP_ID: ${GROUP_ID:-1000}
        USER_ID: ${USER_ID:-1000}
      context: ./
      dockerfile: ./php/php.Dockerfile
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    container_name: php
    tty: true
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/anilibrary
    networks:
      backend:

  database:
    build:
      context: ./
      dockerfile: ./mysql/mysql.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: anilibrary
      MYSQL_USER: u_anilibrary
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-default}
    container_name: database
    tty: true
    volumes:
    - ./runtime/mysql:/var/lib/mysql:rw
    ports:
    - ${MYSQL_PORT:-3306}:3306
    networks:
      backend:

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
    - 7760:80
    networks:
      backend: