<?php

declare(strict_types=1);

return [
    /*-------------------------------------------------------------------------
    | Telegram Token
    |--------------------------------------------------------------------------
    |
    | Telegram bot token.
    |
    */
    'token'       => env('TELEGRAM_TOKEN'),

    /*-------------------------------------------------------------------------
    | Safe Mode
    |--------------------------------------------------------------------------
    |
    | If the webhook mode must validate the incoming IP range is from a telegram server.
    |
    */
    'safe_mode'   => env('APP_ENV', 'local') === 'production',

    /*-------------------------------------------------------------------------
    | Configuration
    |--------------------------------------------------------------------------
    |
    | Extra or specific configurations, bot name or Guzzle client options.
    | All keys must be in snake_case.
    |
    */
    'config'      => [
        'bot_name' => env('TELEGRAM_BOT_NAME'),
    ],

    /*-------------------------------------------------------------------------
    | Routes
    |--------------------------------------------------------------------------
    |
    | Set if the service provider should automatically load
    | handlers from /routes/telegram.php.
    |
    */
    'routes'      => true,

    /*-------------------------------------------------------------------------
    | Mixins
    |--------------------------------------------------------------------------
    |
    | Enable or disable Nutgram mixins.
    |
    */
    'mixins'      => false,

    /*-------------------------------------------------------------------------
    | Namespace
    |--------------------------------------------------------------------------
    |
    | Path to save files generated by nutgram:make command.
    |
    */
    'namespace'   => app_path('Telegram'),

    /*-------------------------------------------------------------------------
    | Log Channel
    |--------------------------------------------------------------------------
    |
    | Set log channel.
    |
    */
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),

    /*-------------------------------------------------------------------------
    | Whitelist
    |--------------------------------------------------------------------------
    |
    | A list of telegram ids that have access to bot, separated by coma.
    |
    */
    'whitelist'   => env('TELEGRAM_WHITELIST', ''),
];

