name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install -qn --no-ansi --no-progress --no-scripts --prefer-dist

      - name: Run Psalm
        run: ./vendor/bin/psalm -c psalm.xml

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --memory-limit=2G

      - name: Run tests
        run: php artisan test --coverage