name: Frontend lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: ./src/yarn.lock

      - name: Install dependencies
        run: |
          yarn set version berry
          yarn config set -H enableTelemetry false
          yarn install --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn prettier-check