name: Frontend lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    strategy:
      matrix:
        node-version: [ 22.x ]
        pnpm-version: [ 10.8 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ./src/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm prettier-check