name: Backend static analysis

on: [ push, pull_request ]

jobs:
  analysis:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: src/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install

      - name: Run Psalm
        run: ./vendor/bin/psalm -c psalm.xml

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --memory-limit=2G