name: Test Anilibrary

on:
  push:
    branches: [ 'master', 'dev' ]
  pull_request:
    branches: [ 'master', 'dev' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: xdebug
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install -qn --no-ansi --no-progress --no-scripts --prefer-dist

      - name: Run tests
        run: php artisan test --coverage